// eslint-disable-next-line max-len
// make an database hardcoded to test the app with data of users with firstname, lastname, role, username, email, preferences, bio, image, likedUsers, dislikedUsers, and matches

export const mentors = [

]
export const mentees = [
  {
    id: 1,
    firstName: 'Ru',
    lastName: 'Paul',
    pronoun: 'He or She',
    role: 'mentor',
    username: 'RuPaul',
    email: 'ruThepaul@mail.com',
    preferences: ['Fullstack', 'Java'],
    bio: 'I want the the best of the best!',
    emoji: '👩🏿‍💻 🇺🇸 🪩',
    image: 'https://time.com/wp-content/uploads/2017/04/time-100-2017-rupaul-miles-aldridge.jpg?w=560',
    likedUsers: [2, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: 1,
    firstName: 'Anna',
    lastName: 'Sorokin',
    pronoun: 'She',
    role: 'mentee',
    username: 'Anna Delvey',
    email: 'anna@sorokin.com',
    preferences: ['frontend', 'JavaScript', 'react'],
    bio: 'Transition from artistic schemes to coding dreams. Lets leave the cons in the past and embark on a tech journey thats legit, innovative, and scam-free? Ready to build a new empire.',
    emoji: '🇺🇸 🏝️ ',
    image: 'https://static01.nyt.com/images/2022/02/17/fashion/14SOROKIN1/14SOROKIN1-jumbo.jpg?quality=75&auto=webp',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: 2,
    firstName: 'Ru',
    lastName: 'Paul',
    pronoun: 'He or She',
    role: 'mentee',
    username: 'RuPaul',
    email: 'ruThepaul@mail.com',
    preferences: ['Fullstack ', 'Java'],
    bio: 'The best of the best I will transform you!',
    emoji: '👩🏿‍💻 🇺🇸 🪩',
    image: 'https://time.com/wp-content/uploads/2017/04/time-100-2017-rupaul-miles-aldridge.jpg?w=560',
    likedUsers: [2, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },

  {
    id: 3,
    firstName: 'Michelle',
    lastName: 'Rodriguez',
    pronoun: 'She ',
    role: 'mentee',
    username: 'Data Tech',
    email: 'michelle@mail.com',
    preferences: ['FBackend ', 'Node.js'],
    bio: 'Im on a mission to find a coding mentor who can guide me through this exciting digital adventure. Lets rewrite the script of my skills and make some binary magic together!.',
    emoji: '🐶  🔥 ',
    image: 'https://animatedtimes.com/wp-content/uploads/2023/03/Michelle-Rodriguez-decent.jpg',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: 4,
    firstName: 'Rihanna',
    lastName: 'Fenty',
    pronoun: 'She',
    role: 'mentee',
    username: 'Riri',
    email: 'riri@gmail.com',
    preferences: ['frontend ', 'JavaScript ', 'react'],
    bio: 'With beats that ignite and fashion that stuns,I aim to unravel codings mysteries, one by one. Awaiting your guidance with anticipation,Rihanna, the Coding Sensation.',
    emoji: '🍟💎 🏝️ ',
    image: 'https://imageio.forbes.com/specials-images/imageserve/5ceec355142c500008f42068/Rihanna-Diamond-Ball-Forbes-Women/0x0.jpg?format=jpg&crop=1950,1950,x32,y257,safe&height=1950&width=1950   ',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: 5,
    firstName: 'Britney',
    lastName: 'Spears',
    pronoun: 'She',
    role: 'mentee',
    username: 'Its_Britney_Bitch',
    email: 'brittan@hotmail.com',
    preferences: ['frontend ', 'JavaScript ', 'react'],
    bio: 'Oops, Im ready to code it again! Im longing for a coding mentor to guide me through the digital terrain."Byte me, baby, one more time!" ',
    emoji: '🇺🇸 🏝️ ',
    image: 'https://www.nzherald.co.nz/resizer/LIgi6nKJC-6rAvbW0PgF-dMaHsw=/576x613/smart/filters:quality(70)/cloudfront-ap-southeast-2.images.arcpublishing.com/nzme/KJHRPO3OMHTRIXR2MGJPUFAAYQ.jpg',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: '6',
    firstName: 'Diana',
    lastName: 'Danelys De Los Santos',
    pronoun: 'She',
    role: 'mentee',
    username: 'Amara La Negra',
    email: 'amara@gmail.com',
    preferences: ['frontend ', 'JavaScript ', 'native'],
    bio: ' Im looking for a coding mentor to help me unlock the digital wonders. Lets blend the rhythm of code with my vibrant spirit and create a harmonious masterpiece that will make the tech world dance to our tune!.',
    emoji: '🇩🇴 🇺🇸 💪🏿 ',
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Amara_La_Negra_Dec_2018.png',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: 7,
    firstName: 'Elisabeth',
    lastName: 'Holmes',
    pronoun: 'She',
    role: 'mentee',
    username: 'New Steve Jobs',
    email: 'eli@gmail.com',
    preferences: ['frontend ', 'JavaScript ', 'react'],
    bio: 'Im a tech wiz in look for a mentor who can guide me in my new carrer mabey we canstart something together',
    emoji: '🇺🇸  🏕️ ',
    image: 'https://cdn.britannica.com/23/181623-050-6D1EC109/Elizabeth-Holmes-Theranos-Inc-company-laboratory-testing-2003.jpg',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  },
  {
    id: 8,
    firstName: 'Beyonce',
    lastName: 'Knowles',
    pronoun: 'She',
    role: 'mentee',
    username: 'Queen_Bey',
    email: 'Queen_Bey@gmail.com',
    preferences: ['frontend ', 'JavaScript ', 'react'],
    bio: 'Bow down, for Queen Bey seeks a mentor in the realm of code!',
    emoji: '🇺🇸 👑 📢 ',
    image: 'https://www.travelnews.se/wp-content/uploads/2023/02/643px-Beyonce_Black_Is_King_Still.png',
    likedUsers: [1, 3, 4],
    dislikedUsers: [5, 6, 7],
    matches: [8, 9, 10]
  }
]

